name: simple_database
description: A simple lightweight wrapper for the SharedPreferences Flutter package. 
version: 1.0.6
homepage: https://github.com/gquarles/simple_database

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: '>=2.0.0 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: