name: simple_database
description: A simple wrapper for shared preferences for storing objects
version: 1.0.0
homepage: https://github.com/gquarles/simple_database

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.7+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: